version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: >-
    dotnet restore

    nuget restore
build:
  verbosity: minimal
artifact:
  path: MetaLog\bin\Release\netstandard2.0\*
  name: ReleaseArtifact
deploy:
  provider: NuGet
  api_key:
    secure: vc7rUEW84l4OwcpHh3cb+8CeSfkYRwzp7h1VFjfHeMtYve2r0erWtueexTARgvxr
  skip_symbols: true
  artifact: /.*\.nupkg/