version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'MetaLog\*.csproj'
  version: '{version}'
  package_version: '{version}'
cache:
  - packages -> **\packages.config

before_build:
- cmd: >-
    dotnet restore

    nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    dotnet pack MetaLog\MetaLog.csproj

artifacts:
  - path: MetaLog\bin\$(configuration)\*.nupkg
    name: NupkgArtifact
deploy:
  provider: NuGet
  api_key:
    secure: GbnKcTtDdY0RbYxlclr1ad4oL0qmge9VN9bkiA8r8PWx5ElCPfKo5m/6cR79cTgG
  skip_symbols: true
  artifact: /.*\.nupkg/
